/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A thin wrapper around u128 that is using strings for JSON encoding/decoding, such that the full u128 range can be used for clients that convert JSON numbers to floats, like JavaScript and jq.
 *
 * # Examples
 *
 * Use `from` to create instances of this and `u128` to get the value out:
 *
 * ``` # use cosmwasm_std::Uint128; let a = Uint128::from(123u128); assert_eq!(a.u128(), 123);
 *
 * let b = Uint128::from(42u64); assert_eq!(b.u128(), 42);
 *
 * let c = Uint128::from(70u32); assert_eq!(c.u128(), 70); ```
 */
export type Uint128 = string;

export interface Batch {
  /**
   * Estimated time when this batch will finish unbonding
   */
  est_unbond_end_time: number;
  /**
   * ID of this batch
   */
  id: number;
  /**
   * Whether this batch has already been reconciled
   */
  reconciled: boolean;
  /**
   * Total amount of shares remaining this batch. Each `ustake` burned = 1 share
   */
  total_shares: Uint128;
  /**
   * Amount of `uluna` in this batch that have not been claimed
   */
  uluna_unclaimed: Uint128;
  [k: string]: unknown;
}
