/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ExecuteMsg =
  | {
      receive: Cw20ReceiveMsg;
    }
  | {
      bond: {
        receiver?: string | null;
        [k: string]: unknown;
      };
    }
  | {
      withdraw_unbonded: {
        receiver?: string | null;
        [k: string]: unknown;
      };
    }
  | {
      add_validator: {
        validator: string;
        [k: string]: unknown;
      };
    }
  | {
      remove_validator: {
        validator: string;
        [k: string]: unknown;
      };
    }
  | {
      transfer_ownership: {
        new_owner: string;
        [k: string]: unknown;
      };
    }
  | {
      accept_ownership: {
        [k: string]: unknown;
      };
    }
  | {
      harvest: {
        [k: string]: unknown;
      };
    }
  | {
      rebalance: {
        [k: string]: unknown;
      };
    }
  | {
      reconcile: {
        [k: string]: unknown;
      };
    }
  | {
      submit_batch: {
        [k: string]: unknown;
      };
    }
  | {
      callback: CallbackMsg;
    }
  | {
      update_config: {
        /**
         * Contract address where fees are sent
         */
        protocol_fee_contract?: string | null;
        /**
         * Fees that are being applied during reinvest of staking rewards
         */
        protocol_reward_fee?: Decimal | null;
        [k: string]: unknown;
      };
    };
/**
 * A thin wrapper around u128 that is using strings for JSON encoding/decoding, such that the full u128 range can be used for clients that convert JSON numbers to floats, like JavaScript and jq.
 *
 * # Examples
 *
 * Use `from` to create instances of this and `u128` to get the value out:
 *
 * ``` # use cosmwasm_std::Uint128; let a = Uint128::from(123u128); assert_eq!(a.u128(), 123);
 *
 * let b = Uint128::from(42u64); assert_eq!(b.u128(), 42);
 *
 * let c = Uint128::from(70u32); assert_eq!(c.u128(), 70); ```
 */
export type Uint128 = string;
/**
 * Binary is a wrapper around Vec<u8> to add base64 de/serialization with serde. It also adds some helper methods to help encode inline.
 *
 * This is only needed as serde-json-{core,wasm} has a horrible encoding for Vec<u8>
 */
export type Binary = string;
export type CallbackMsg = {
  reinvest: {
    [k: string]: unknown;
  };
};
/**
 * A fixed-point decimal value with 18 fractional digits, i.e. Decimal(1_000_000_000_000_000_000) == 1.0
 *
 * The greatest possible value that can be represented is 340282366920938463463.374607431768211455 (which is (2^128 - 1) / 10^18)
 */
export type Decimal = string;

/**
 * Cw20ReceiveMsg should be de/serialized under `Receive()` variant in a ExecuteMsg
 */
export interface Cw20ReceiveMsg {
  amount: Uint128;
  msg: Binary;
  sender: string;
  [k: string]: unknown;
}
