/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type QueryMsg =
  | {
      config: {
        [k: string]: unknown;
      };
    }
  | {
      state: {
        [k: string]: unknown;
      };
    }
  | {
      pending_batch: {
        [k: string]: unknown;
      };
    }
  | {
      previous_batch: number;
    }
  | {
      previous_batches: {
        limit?: number | null;
        start_after?: number | null;
        [k: string]: unknown;
      };
    }
  | {
      unbond_requests_by_batch: {
        id: number;
        limit?: number | null;
        start_after?: string | null;
        [k: string]: unknown;
      };
    }
  | {
      unbond_requests_by_user: {
        limit?: number | null;
        start_after?: number | null;
        user: string;
        [k: string]: unknown;
      };
    };
